import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

// Import and configure fonts
const inter = Inter({ subsets: ["latin"], variable: '--font-inter', display: 'swap' });
const roboto_mono = Roboto_Mono({ subsets: ["latin"], variable: '--font-roboto-mono', display: 'swap' });

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(inter.className, roboto_mono.className)}>
      <body>{children}</body>
    </html>
  );
}
